#Role user
sudo: required
#OS yang digunakan Precies,trusty,Xenial
dist: trusty 
#Bahasa yang digunakan
language: php
#Versi bahasa yagn digunakan
php:
  - 7.1
  - 7.2
#Branch apa saja yang mau digunakan
branches: 
  only:
    - master
    - develop

before install:
  - wget https://phar.phpunit.de/phpunit-6.5.phar
  - chmod +x phpunit-6.5.phar
  
  
install:
  - sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
#Sebelum script dijalankan
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
#script dieksekusi
script:
  - ./vendor/phpunit
#Setelah eksekusi selesai
after_success:


